### ISSUE TITLE
Query strings in script urls aren't handled well

### ISSUE THREAD

**Issue by greglittlefield-wf** [sethladd/dart_to_js_script_rewriter#13]
`.js` is added to the end of script URLs when they are rewritten, even when the URLs contain query strings.

For example:

Input:
```html
<script type="application/dart" src="entrypoint.dart?cache_busting_query"></script>
```

Expected output:
```html
<script src="entrypoint.dart.js?cache_busting_query"></script>
```

Actual output:
```html
<script src="entrypoint.dart?cache_busting_query.js"></script>
```

**Comment by sethladd** [comment]
Thanks for the report! PR's definitely welcome.

in fact, if yall are using this, I can transfer this repo to you.

**Comment by sethladd** [comment]
I'd like to publish a 1.0 version with this fix. Interested in sending over a patch?

**Comment by greglittlefield-wf** [comment]
Yup, I'll submit one today!

**Comment by greglittlefield-wf** [comment]
Also, we're definitely open to transferring the repo to the https://github.com/Workiva organization. Would you want to be kept as an "owner"?

**Comment by sethladd** [comment]
> Also, we're definitely open to transferring the repo to the https://github.com/Workiva organization.

Cool! Very nice to see it land in good hands :)

> Would you want to be kept as an "owner"?

No need, but appreciate the offer!
