### ISSUE TITLE
Conflicts with Angular Transformer

### ISSUE THREAD

**Issue by NicholasTuck** [sethladd/dart_to_js_script_rewriter#2]
Hard to identify if this is a dart to js script rewriter or an angular transformer problem but I thought I would start here.

If I have the dart_to_js_script_rewriter transformer first and then the angular transformer, the release pub build version causes errors at run time.  The error is always that a method is missing in an angular controller, but it only happens when this transformer is first.

I have it happening in 2 fairly simple projects.

**Comment by sethladd** [comment]
Unfortunately, I don't think I'm going to get to this. AngularDart 1.0 is more or less paused in favor of AngularDart 2.0. So assuming this is obsolete. Happy to take a patch if one becomes available, though.
