### ISSUE TITLE
don't think the csp option is needed anymore

### ISSUE THREAD

**Issue by devoncarew** [sethladd/dart_to_js_script_rewriter#4]
With a ~recent change, dart2js no longer generates both the regular and the csp JS. We user need to specify which type to generate (and the output file name). So, I think generally the csp file will no longer be call `precompiled`.

https://github.com/sethladd/dart_to_js_script_rewriter/blob/master/lib/dart_to_js_script_rewriter.dart#L52

**Comment by devoncarew** [comment]
Should probably just be deprecated or removed?

**Comment by monkeysecurity** [comment]
+1

**Comment by sethladd** [comment]
Patches welcome!
