### ISSUE TITLE
corner case behavior when trying to debug javascript

### ISSUE THREAD

**Issue by devoncarew** [sethladd/dart_to_js_script_rewriter#7]
I ran into a corner case behavior when trying to debug the compiled javascript app. It was optimized - which is super hard to debug. So I built the app with `--mode=debug`. It no longer started up, because the index.html file was not re-written by this transformer.

Note that I am not using the `browser` packages `dart.js` file; I use this transformer instead.

Not sure what a fix would be -

**Comment by sethladd** [comment]
interesting... I didn't realize that `pub build` doesn't just delete the entire build/ dir.

I assume 'built with app' means `pub build` ?

**Comment by devoncarew** [comment]
Yup; using `pub build` meant I could see the problem in the compiled app (what I was debugging), but had a hard time because of the minification. `pub build --mode=debug` built the debuggable version of the app but this transformer didn't run on the index.html file; the app didn't start.

I realized I could have worked around it by changing the `foo.dart` application/dart reference to the compiled ref - foo.dart.js.

**Comment by sethladd** [comment]
I was confused why this didn't work for you in debug mode. Then I saw this: `Note that I am not using the browser packages dart.js file; I use this transformer instead.`

You can leave the `dart.js` file in your `index.html`, because this transformer removes the `dart.js` reference when you do a production build.

**Comment by devoncarew** [comment]
Yeah, I should probably just leave `browser` in (perhaps move it to a dev dependency).

**Comment by sethladd** [comment]
Yes, leave browser's dart.js in your HTML and this transformer will remove it. Or should. If it doesn't, it's a bug in this transformer.
